version: "3"

services:
  elf-go:
    restart: always
    image: alazalaz/elf-go:v1
    container_name: elf-go
    volumes:
      - ./example/app/config/conf-for-docker.yaml:/config/conf.yaml:ro
    network_mode: bridge
    ports:
      - 7070:7070
    logging:
      driver: json-file
      options:
        max-size: "100m"
        max-file: "10"