#系统配置
sys:
  debug: true
  listenPort: 7071
#配置文件
redis:
  ip: 127.0.0.1
  port: 6379
#logrus日志
logrus:
  level: 6
#  WriteToFilePath: /Users/zhangxiong/work/logs/elf.log
#数据库配置，干掉了主从模式，直接使用配置多个db的模式，有点是简单
mysql:
  default:
    ip: 127.0.0.1
    port: 3306
    user: elf2
    password: 123456
    db: test
  app2:
    ip: 127.0.0.1
    port: 3306
    user: elf2
    password: 123456
    db: test
