#系统配置
sys:
  debug: true
#配置文件
redis:
  ip: 127.0.0.1
  port: 6379
#数据库配置，支持多db，多主从
mysql:
  default:
    master: #主库
      - #可以配置多个主库
        ip: 127.0.0.1
        port: 3306
        user: root
        password: 123456
        db: test
    slaver: #从库
      - #可以配置多个从库
        ip: 127.0.0.1
        port: 3306
        user: root
        password: 123456
        db: test
      - #可以配置多个从库
        ip: 127.0.0.1
        port: 3306
        user: root
        password: 123456
        db: test
  backend:
    master: #主库
      - #可以配置多个主库
        ip: 127.0.0.1
        port: 3306
        user: root
        password: 123456
        db: test3
    slaver: #从库
      - #可以配置多个从库
        ip: 127.0.0.1
        port: 3306
        user: root
        password: 123456
        db: test4
